POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
POST http://localhost:3000/api/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "",
    "password": ""
}

###
DELETE http://localhost:3000/api/sauce/627ab2fd3264a3b6a1da43e3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyN2E0YmZkMzI2NjVhYjM5YjYzNmQyMyIsImlhdCI6MTQ5NjQ5NjQwOCwiZXhwIjoxNDk2NDk2NjA4fQ.
